# ---------- Development Stage ----------
FROM node:20

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias dentro del contenedor
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto Vite
EXPOSE 5173

# Comando para hot reload
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
